services:
  - type: web
    name: upendo-bakery
    env: python
    plan: free
    buildCommand: |
      echo "Forcing pip installation and avoiding Poetry..."
      export POETRY_VIRTUALENVS_CREATE=false
      export POETRY_NO_INTERACTION=1
      export PIP_NO_CACHE_DIR=1
      export PIP_DISABLE_PIP_VERSION_CHECK=1
      export POETRY_DISABLE=1
      pip install --no-cache-dir -r requirements.txt
    startCommand: |
      python manage.py migrate
      gunicorn upendo_bakery.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: POETRY_VIRTUALENVS_CREATE
        value: false
      - key: POETRY_NO_INTERACTION
        value: 1
      - key: PIP_NO_CACHE_DIR
        value: 1
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: 1
      - key: POETRY_DISABLE
        value: 1
      - key: DJANGO_SETTINGS_MODULE
        value: upendo_bakery.settings_prod
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: upendo-bakery.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: upendo-bakery-db
          property: connectionString
    packages:
      - libjpeg-dev
      - libpng-dev
      - libfreetype6-dev
      - zlib1g-dev
      - libjpeg62-turbo-dev

databases:
  - name: upendo-bakery-db
    databaseName: upendo_bakery
    user: upendo_bakery_user
    plan: free 