services:
  - type: web
    name: BK_SMS-10
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: >
      python manage.py setup_database &&
      python manage.py create_default_admin &&
      python manage.py create_default_categories &&
      python manage.py collectstatic --noinput &&
      gunicorn upendo_bakery.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: upendo_bakery.settings_prod
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: bk-sms-10.onrender.com
      - key: RENDER_EXTERNAL_HOSTNAME
        value: bk-sms-10.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: bk-sms-10-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health/
    autoDeploy: true

databases:
  - name: bk-sms-10-db
    databaseName: bk_sms_10
    user: bk_sms_10_user
    plan: free
    ipAllowList: [] 