services:
  - type: web
    name: BK_SMS-4
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: upendo_bakery.settings_prod
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: bk-sms-4.onrender.com,upendo-bakery.onrender.com
      - key: RENDER_EXTERNAL_HOSTNAME
        value: bk-sms-4.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: bk-sms-4-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health/
    autoDeploy: true

databases:
  - name: bk-sms-4-db
    databaseName: bk_sms_4
    user: bk_sms_4_user
    plan: free
    ipAllowList: [] 