services:
  - type: web
    name: bk-sms
    env: python
    plan: free
    buildCommand: |
      echo "🚀 Starting build process..."
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      
      echo "🔄 Setting up static files..."
      mkdir -p staticfiles
      
      echo "🛠️  Running migrations..."
      python manage.py migrate --noinput
      
      echo "👤 Creating default admin..."
      python manage.py create_default_admin
      
      echo "🗂️  Creating default categories..."
      python manage.py create_default_categories
      
      echo "📦 Collecting static files..."
      python manage.py collectstatic --noinput --clear
      
      echo "✅ Build completed successfully!"
      
    startCommand: |
      echo "🚀 Starting application..."
      gunicorn upendo_bakery.wsgi:application --bind 0.0.0.0:$PORT
      
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: upendo_bakery.settings_prod
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: true
      - key: DATABASE_URL
        fromDatabase:
          name: bk-sms-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
      - key: DISABLE_COLLECTSTATIC
        value: "0"
      - key: WHITENOISE_AUTOREFRESH
        value: "True"
        
    healthCheckPath: /health/
    autoDeploy: true

    # Add buildpacks for Python and Node.js (if needed)
    buildpacks:
      - https://github.com/heroku/heroku-buildpack-python
      - https://github.com/heroku/heroku-buildpack-nodejs

    # Add a post-deploy script if needed
    # postDeploy: 
    #   ./post_deploy.sh

databases:
  - name: bk-sms-db
    databaseName: bk_sms
    user: bk_sms_user
    plan: free
    ipAllowList: []
    # Add database configuration
    configuration:
      maxConnections: 100
      sharedBuffers: 100MB
      workMem: 10MB
      maintenanceWorkMem: 50MB
      maxParallelWorkers: 2