services:
  - type: web
    name: bk-sms
    env: python
    plan: free
    
    # Make build.sh executable and run it
    buildCommand: |
      echo "🚀 Starting build process..."
      chmod +x build.sh
      ./build.sh
    
    # Start command is now handled by build.sh
    startCommand: ""
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.18  # Match the version in runtime.txt
      - key: DJANGO_SETTINGS_MODULE
        value: upendo_bakery.settings_prod
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"  # For now, restrict to specific domains in production
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: true
      - key: DATABASE_URL
        fromDatabase:
          name: bk-sms-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
      - key: DISABLE_COLLECTSTATIC
        value: "0"
      - key: WHITENOISE_AUTOREFRESH
        value: "True"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONHASHSEED
        value: "random"
    
    # Health check configuration
    healthCheckPath: /health/
    healthCheckTimeout: 30s
    autoDeploy: true
    
    # Buildpacks for Python
    buildpacks:
      - https://github.com/heroku/heroku-buildpack-python
    
    # Resource allocation (adjust based on your needs)
    resources:
      cpu: 1
      memory: 1GB
      disk: 10GB

databases:
  - name: bk-sms-db
    databaseName: bk_sms
    user: bk_sms_user
    plan: free
    ipAllowList: []
    configuration:
      maxConnections: 100
      sharedBuffers: 100MB
      workMem: 10MB
      maintenanceWorkMem: 50MB
      maxParallelWorkers: 2
    
    # Database backup settings (adjust as needed)
    backupRetentionDays: 7
    backupStartMinute: 0
    backupStartHour: 2
    backupDayOfWeek: 0  # Sunday