# render.yaml
databases:
  - name: bk-sms-db
    databaseName: upendo_bakery
    user: upendo_user
    plan: free

services:
  - type: web
    name: bk-sms
    env: python
    plan: free

    buildCommand: |
      echo "🚀 Starting build process..."
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      mkdir -p staticfiles/health
      echo "<html><body><h1>Health Check</h1><p>OK</p></body></html>" > staticfiles/health/index.html

    startCommand: gunicorn upendo_bakery.wsgi:application --bind 0.0.0.0:$PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.18
      - key: DJANGO_SETTINGS_MODULE
        value: upendo_bakery.settings_prod
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: bk-sms-db
          property: connectionString

    healthCheckPath: /health/
    autoDeploy: true

    buildpacks:
      - https://github.com/heroku/heroku-buildpack-python
