services:
  - type: web
    name: bk-sms
    env: python
    plan: free
    buildCommand: |
      echo "🚀 Starting build process..."
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py create_default_admin
      python manage.py create_default_categories
      python manage.py collectstatic --noinput --clear
    startCommand: gunicorn upendo_bakery.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: upendo_bakery.settings_prod
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: true
      - key: DATABASE_URL
        fromDatabase:
          name: bk-sms-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health/
    autoDeploy: true

databases:
  - name: bk-sms-db
    databaseName: bk_sms
    user: bk_sms_user
    plan: free
    ipAllowList: []