# Render Configuration for Upendo Bakery
# This file defines the infrastructure for the Django application

services:
  - type: web
    name: bk-sms
    env: python
    plan: free
    
    # Build command will be handled by build.sh
    buildCommand: |
      echo "🚀 Starting build process..."
      chmod +x build.sh
      ./build.sh
    
    # Start command is handled by build.sh
    startCommand: ""
    
    # Environment variables
    envVars:
      # Python configuration
      - key: PYTHON_VERSION
        value: 3.11.18  # Must match runtime.txt
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONHASHSEED
        value: "random"
      
      # Django configuration
      - key: DJANGO_SETTINGS_MODULE
        value: upendo_bakery.settings_prod
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"  # TODO: Replace with actual domain in production
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: true
      
      # Database configuration
      - key: DATABASE_URL
        fromDatabase:
          name: bk-sms-db
          property: connectionString
      - key: Database_URL
        fromDatabase:
          name: bk-sms-db
          property: connectionString
      
      # Static files configuration
      - key: DISABLE_COLLECTSTATIC
        value: "0"
      - key: WHITENOISE_AUTOREFRESH
        value: "True"
      
      # Application configuration
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
    
    # Health check configuration
    healthCheckPath: /health/
    healthCheckTimeout: 30s
    autoDeploy: true
    
    # Buildpacks for Python
    buildpacks:
      - https://github.com/heroku/heroku-buildpack-python
    
    # Resource allocation
    resources:
      cpu: 1
      memory: 1GB
      disk: 10GB

databases:
  - name: bk-sms-db
    databaseName: bk_sms
    user: bk_sms_user
    plan: free
    ipAllowList: []
    
    # Database configuration
    configuration:
      maxConnections: 100
      sharedBuffers: 100MB
      workMem: 10MB
      maintenanceWorkMem: 50MB
      maxParallelWorkers: 2
    
    # Backup settings
    backupRetentionDays: 7
    backupStartMinute: 0
    backupStartHour: 2
    backupDayOfWeek: 0  # Sunday