services:
  - type: web
    name: upendo-bakery
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: upendo_bakery.settings_prod
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: bk-sms-1.onrender.com,upendo-bakery.onrender.com
      - key: RENDER_EXTERNAL_HOSTNAME
        value: bk-sms-1.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: upendo-bakery-db
          property: connectionString

databases:
  - name: upendo-bakery-db
    databaseName: upendo_bakery
    user: upendo_bakery_user
    plan: free 