services:
  - type: web
    name: BK_SMS-4
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: >
      python manage.py migrate &&
      python manage.py ensure_data_persistence &&
      python manage.py create_default_admin &&
      python manage.py create_default_categories &&
      python manage.py setup_render_database &&
      python manage.py collectstatic --noinput &&
      gunicorn upendo_bakery.wsgi:application --config gunicorn_config.py
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: upendo_bakery.settings_prod
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: bk-sms-4.onrender.com,upendo-bakery.onrender.com
      - key: RENDER_EXTERNAL_HOSTNAME
        value: bk-sms-4.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: bk-sms-4-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health/
    autoDeploy: true

databases:
  - name: bk-sms-4-db
    databaseName: bk_sms_4
    user: bk_sms_4_user
    plan: free
    ipAllowList: [] 