# Generated by Django 5.2.1 on 2025-06-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_settings_setting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('dozen', 'Dozen'), ('pack', 'Pack'), ('box', 'Box'), ('tray', 'Tray')], default='piece', max_length=10),
        ),
    ]
