# Generated by Django 5.2.1 on 2025-06-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_performance_indexes'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_roles') THEN
                    CREATE TYPE user_roles AS ENUM ('admin', 'manager', 'cashier', 'baker', 'delivery');
                END IF;
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
            """,
            "DROP TYPE IF EXISTS user_roles;"
        ),
    ]
