# Generated by Django 5.2.1 on 2025-06-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20250618_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_in_inventory',
            field=models.BooleanField(default=True, help_text='Show in Inventory and POS'),
        ),
    ]
